use_frameworks!
platform :ios, '9.0'
target 'AckooSDK_Example' do
  pod 'AckooSDK', :path => '../'

  target 'AckooSDK_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  
    
  end
end
